# Generated by Django 4.2 on 2023-04-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subhakaarya_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['rank']},
        ),
    ]
