# Generated by Django 4.2 on 2023-04-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhakaarya_app', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
