# Generated by Django 4.2 on 2023-06-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subhakaarya_app', '0004_alter_service_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='service',
        ),
        migrations.AddField(
            model_name='event',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subhakaarya_app.plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='services',
            field=models.ManyToManyField(to='subhakaarya_app.service'),
        ),
        migrations.DeleteModel(
            name='EventPlan',
        ),
    ]
