# Generated by Django 4.2 on 2023-06-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subhakaarya_app', '0005_remove_event_plans_remove_plan_service_event_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('locations', models.TextField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='uploads/vendor-services/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subhakaarya_app.service')),
            ],
        ),
    ]
