# Generated by Django 4.2 on 2023-06-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhakaarya_app', '0006_vendorservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='environment',
            field=models.TextField(),
        ),
    ]
