# Generated by Django 4.2 on 2023-07-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_vendor_options_vendor_address_vendor_phone'),
        ('subhakaarya_app', '0007_event_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.vendor'),
            preserve_default=False,
        ),
    ]
