# Generated by Django 4.2 on 2023-10-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhakaarya_app', '0008_vendorservice_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendorlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vedor_name', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='uploads/vendorlist/')),
            ],
        ),
    ]
